# Generated by Django 4.0.4 on 2022-05-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('property', models.CharField(max_length=20)),
            ],
        ),
    ]
