# Generated by Django 4.0.4 on 2022-05-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(default='Monster', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
