# Generated by Django 4.0.4 on 2022-05-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_card_card_type_alter_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
