# Generated by Django 4.0.4 on 2022-05-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_card_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=40)),
                ('copies', models.CharField(choices=[(1, 'Single'), (2, 'Pair'), (3, 'Playset')], default=1, max_length=1)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card')),
            ],
        ),
    ]
