# Generated by Django 4.0.4 on 2022-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_card_atk_alter_card_attribute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owned',
            options={'ordering': ['set']},
        ),
        migrations.AlterField(
            model_name='owned',
            name='copies',
            field=models.CharField(choices=[('1', 'Single (1)'), ('2', 'Pair (2)'), ('3', 'Playset (3)')], default='1', max_length=1),
        ),
    ]
