# Generated by Django 4.0.4 on 2022-05-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_owned_options_alter_owned_copies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owned',
            old_name='copy',
            new_name='card',
        ),
    ]
