# Generated by Django 4.0.4 on 2022-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_effecttype_card_effect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effecttype',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
