# Generated by Django 4.0.4 on 2022-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_effecttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='effecttype',
            name='description',
            field=models.TextField(default='N/A', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='effecttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
